# Bandit is a security linter designed to find common security issues in Python code.
# This action will run Bandit on your codebase.
# The results of the scan will be found under the Security tab of your repository.

name: Bandit
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '16 2 * * 6'

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install bandit bandit-sarif-formatter
      
      - name: Run Scan
        run: |
          source venv/bin/activate
          bandit -r .

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif  # Se você salvar os resultados do Bandit em formato SARIF

